### ISSUE TITLE
Function doesn't work after the web autho 

### ISSUE THREAD

**Issue by fahadwar** [TrevTV/mb_CopySpotify#5]
I installed the latest and restarted musicbee and its still I see the error. 

>_MusicBee v3.4.7805.33439D  (Win10.0), 25 Dec 2021 6:36:

>System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MusicBeePlugin.Plugin.MenuClicked(Object sender, EventArgs args)
   at #=zyaDvjP7rivWYyDUVEiYzl8WN4do7.#=zuk052KY=(Object #=zrGRMGbM=, EventArgs #=zJqXIhV8=)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)_

**Comment by TrevTV** [comment]
Old issue but I am unable to replicate this, though if you still need help feel free to reopen this issue
